### ISSUE TITLE
교수가 학생의 출결 정보 변경 시 학생에게 알림이 가도록 하는 기능 추가

### ISSUE THREAD

**Issue by Planybirth** [SUVID-18/check_attendance_student#58]
## 추가를 제안하고 싶은 기능에 대한 간략한 설명
어떤 기능을 원하는지 적어주세요.

교수가 학생의 출결 정보를 직접 수정할 경우
출결 정보가 변경되었음을 알리는 알람이 해당 학생에게 전달되는 기능입니다.

화면 구성은 간단한 팝업 메세지로 구현하면 괜찮을 것 같습니다.

**Comment by sun30812** [comment]
해당 기능을 정상적으로 수행하려면 아래와 같은 요구사항이 필요할 것 같어

- 과목 데이터베이스에 수강 대상자 정보 등록 -> 대상자는 학번으로 식별하면 될 듯
- 앱에서 알림을 수신하기 위한 설정 -> [참고문서](https://firebase.google.com/docs/cloud-messaging/flutter/client?authuser=0&hl=ko)
