### ISSUE TITLE
학생용 출결 앱 환경설정 페이지 구현

### ISSUE THREAD

**Issue by 000hgf** [SUVID-18/check_attendance_student#7]
계정 정보 확인, 로그아웃 및 기기 변경을 할 수 있는 환경 설정 탭 구현입니다.

**Comment by 000hgf** [comment]
@sun30812 근데 기기변경 신청을 이전 기기에서 로그인을 해서 신청해야하나요?

**Comment by sun30812** [comment]
> @sun30812 근데 기기변경 신청을 이전 기기에서 로그인을 해서 신청해야하나요?

기변하기 전애 이전 기기에서 신청하면 될 것 같음.

로그인 페이지에도 기기를 변경하셨나요? 같은거 버튼만 추가할까?

**Comment by 000hgf** [comment]
> > @sun30812 근데 기기변경 신청을 이전 기기에서 로그인을 해서 신청해야하나요?
> 
> 기변하기 전에 이전 기기에서 신청하면 될 것 같음.
> 
> 로그인 페이지(#6)에도 기기를 변경하셨나요? 같은거 버튼 추가해야 돨 것 같기도 하네

근데 신청을 이전 기기에서 하면 핸드폰 분실같은 이유로 기기변경신청은 불가하잖아
그냥 로그인 페이지에만 기기변경 신청 만들면 안됨?

**Comment by sun30812** [comment]
> > > @sun30812 근데 기기변경 신청을 이전 기기에서 로그인을 해서 신청해야하나요?
> 
> > 
> 
> > 기변하기 전에 이전 기기에서 신청하면 될 것 같음.
> 
> > 
> 
> > 로그인 페이지(#6)에도 기기를 변경하셨나요? 같은거 버튼 추가해야 돨 것 같기도 하네
> 
> 
> 
> 근데 신청을 이전 기기에서 하면 핸드폰 분실같은 이유로 기기변경신청은 불가하잖아
> 
> 그냥 로그인 페이지에만 기기변경 신청 만들면 안됨?

그러자

**Comment by 000hgf** [comment]
> 그럼 로그인 페이지에만 추가하자

그렇게 하겠슴다~
